Repository GDSC-PKNU-Official/pknu-notice-front, pull requests merged in 2023-10, with the labels that each got.

#257 Feat/#246: 사이드바 구현 & 부림이 앱 아이콘 백경이 버젼 추가
  public/assets/baekgyeong-speaker.png
  public/assets/baekgyeong-whalebe.png
  public/assets/pknu.png
  public/icons/icon-128x128.png
  public/icons/icon-144x144.png
  public/icons/icon-152x152.png
  public/icons/icon-192x192.png
  public/icons/icon-384x384.png
  public/icons/icon-48x48.png
  public/icons/icon-512x512.png
  public/icons/icon-72x72.png
  public/icons/icon-96x96.png
  public/tmp_icons/icon-128x128.png
  public/tmp_icons/icon-144x144.png
  public/tmp_icons/icon-152x152.png
  public/tmp_icons/icon-192x192.png
  public/tmp_icons/icon-384x384.png
  public/tmp_icons/icon-48x48.png
  public/tmp_icons/icon-512x512.png
  public/tmp_icons/icon-72x72.png
  public/tmp_icons/icon-96x96.png
  src/@types/styles/icon.ts
  src/@types/styles/image.ts
  src/@types/styles/size.ts
  src/App.tsx
  src/components/Header/index.tsx
  src/components/Icon/index.tsx
  src/components/Image/index.tsx
  src/components/SideBar/Content/index.tsx
  src/components/SideBar/index.tsx
  src/constants/assets-path.ts
  src/constants/sidebar.ts
  src/constants/tip.ts
  src/pages/Tip/index.tsx
Labels: ⚙️ config, ✨ feat, ⚒️ chore

#259 Fix/#258: ios에서 카카오맵 길찾기 기능을 사용할 수 없는 문제 해결 & UI,UX 관련 피드백 반영
  src/App.tsx
  src/constants/pknu-map.ts
  src/contexts/overlays.ts
  src/hooks/useLocationHandler.ts
  src/hooks/useOverlays.ts
  src/hooks/useUserLocation.ts
  src/pages/Map/Provider/index.tsx
  src/pages/Map/components/BuildingFilterButtons.tsx
  src/pages/Map/components/MapHeader.tsx
  src/pages/Map/components/PknuBuildingNumbers.tsx
  src/pages/Map/handlers/boundary.ts
  src/pages/Map/handlers/distance-handler.ts
  src/pages/Map/handlers/distance.ts
  src/pages/Map/handlers/index.ts
  src/pages/Map/handlers/limit-handler.ts
  src/pages/Map/handlers/ovelary.ts
  src/pages/Map/handlers/overlay-handler.ts
  src/pages/Map/index.tsx
Labels: ⚙️ config, 🧑‍🔧 refactor, ⚒️ chore

#260 부림이 v0.38 배포
  public/assets/baekgyeong-speaker.png
  public/assets/baekgyeong-whalebe.png
  public/assets/pknu.png
  public/icons/icon-128x128.png
  public/icons/icon-144x144.png
  public/icons/icon-152x152.png
  public/icons/icon-192x192.png
  public/icons/icon-384x384.png
  public/icons/icon-48x48.png
  public/icons/icon-512x512.png
  public/icons/icon-72x72.png
  public/icons/icon-96x96.png
  public/tmp_icons/icon-128x128.png
  public/tmp_icons/icon-144x144.png
  public/tmp_icons/icon-152x152.png
  public/tmp_icons/icon-192x192.png
  public/tmp_icons/icon-384x384.png
  public/tmp_icons/icon-48x48.png
  public/tmp_icons/icon-512x512.png
  public/tmp_icons/icon-72x72.png
  public/tmp_icons/icon-96x96.png
  src/@types/styles/icon.ts
  src/@types/styles/image.ts
  src/@types/styles/size.ts
  src/App.tsx
  src/components/Header/index.tsx
  src/components/Icon/index.tsx
  src/components/Image/index.tsx
  src/components/SideBar/Content/index.tsx
  src/components/SideBar/index.tsx
  src/constants/assets-path.ts
  src/constants/pknu-map.ts
  src/constants/sidebar.ts
  src/constants/tip.ts
  src/contexts/overlays.ts
  src/hooks/useLocationHandler.ts
  src/hooks/useOverlays.ts
  src/hooks/useUserLocation.ts
  src/pages/Map/Provider/index.tsx
  src/pages/Map/components/BuildingFilterButtons.tsx
  src/pages/Map/components/MapHeader.tsx
  src/pages/Map/components/PknuBuildingNumbers.tsx
  src/pages/Map/handlers/boundary.ts
  src/pages/Map/handlers/distance-handler.ts
  src/pages/Map/handlers/distance.ts
  src/pages/Map/handlers/index.ts
  src/pages/Map/handlers/limit-handler.ts
  src/pages/Map/handlers/ovelary.ts
  src/pages/Map/handlers/overlay-handler.ts
  src/pages/Map/index.tsx
  src/pages/Tip/index.tsx
Labels: 🖥️ deploy

#262 Chore: 백경이 이미지 배경색 흰색으로 변경
  public/icons/icon-128x128.png
  public/icons/icon-144x144.png
  public/icons/icon-152x152.png
  public/icons/icon-192x192.png
  public/icons/icon-384x384.png
  public/icons/icon-48x48.png
  public/icons/icon-512x512.png
  public/icons/icon-72x72.png
  public/icons/icon-96x96.png
Labels: ⚒️ chore

#263 부림이 v0.39 배포
  public/icons/icon-128x128.png
  public/icons/icon-144x144.png
  public/icons/icon-152x152.png
  public/icons/icon-192x192.png
  public/icons/icon-384x384.png
  public/icons/icon-48x48.png
  public/icons/icon-512x512.png
  public/icons/icon-72x72.png
  public/icons/icon-96x96.png
Labels: 🖥️ deploy

#266 Config: 타이틀 변경
  index.html
Labels: ⚙️ config

#270 Style/#267: 건물번호 필터링 버튼 위치 변경 && 토스트 메세지 구현
  src/@types/styles/icon.ts
  src/@types/toasts.ts
  src/components/Icon/index.tsx
  src/components/Modal/SuggestionModal/index.tsx
  src/components/Provider/Toast/index.tsx
  src/components/Toast/Toasts/index.tsx
  src/components/Toast/index.tsx
  src/constants/pknu-map.ts
  src/constants/placeholder-message.ts
  src/constants/toast-message.ts
  src/contexts/toasts.ts
  src/hooks/useLocationHandler.ts
  src/hooks/useOverlays.ts
  src/hooks/useToast.ts
  src/main.tsx
  src/pages/Map/components/BuildingFilterButtons.tsx
  src/pages/Map/components/FilterButtons.tsx
  src/pages/Map/components/MapHeader.tsx
  src/pages/Map/components/RefreshButtons.tsx
  src/pages/Map/components/index.ts
  src/pages/Map/handlers/boundary.ts
  src/pages/Map/handlers/distance.ts
  src/pages/Map/handlers/index.ts
  src/pages/Map/handlers/overlays.ts
  src/pages/Map/index.tsx
  src/utils/map/check-location.ts
  src/utils/map/index.ts
  src/utils/map/location-permission.ts
Labels: ✨ feat, 💇‍♂️ style

#277 부림이 v0.40 배포
  index.html
  src/@types/styles/icon.ts
  src/@types/toasts.ts
  src/components/Button/index.tsx
  src/components/Carousel/index.tsx
  src/components/Icon/index.tsx
  src/components/List/DepartmentList/DepartmentItem.tsx
  src/components/Modal/SuggestionModal/index.tsx
  src/components/Provider/Toast/index.tsx
  src/components/Toast/Toasts/index.tsx
  src/components/Toast/index.tsx
  src/constants/modal-messages.ts
  src/constants/pknu-map.ts
  src/constants/placeholder-message.ts
  src/constants/toast-message.ts
  src/contexts/toasts.ts
  src/hooks/useLocationHandler.ts
  src/hooks/useOverlays.ts
  src/hooks/useToast.ts
  src/main.tsx
  src/mocks/handlers/announceHandlers.ts
  src/pages/Map/components/BuildingFilterButtons.tsx
  src/pages/Map/components/FilterButtons.tsx
  src/pages/Map/components/MapHeader.tsx
  src/pages/Map/components/RefreshButtons.tsx
  src/pages/Map/components/index.ts
  src/pages/Map/handlers/boundary.ts
  src/pages/Map/handlers/distance.ts
  src/pages/Map/handlers/index.ts
  src/pages/Map/handlers/overlays.ts
  src/pages/Map/index.tsx
  src/styles/ThemeProvider/theme.ts
  src/styles/emotion.d.ts
  src/utils/map/check-location.ts
  src/utils/map/index.ts
  src/utils/map/location-permission.ts
Labels: 🖥️ deploy

#280 부림이 v0.4.1 배포
  src/pages/Map/handlers/overlays.ts
Labels: 🖥️ deploy

#281 부림이 v0.4.2 배포
  README.md
Labels: 🖥️ deploy
