Repository GDSC-PKNU-Official/pknu-notice-front, pull requests merged in 2023-11, with the labels that each got.

#274 Style/#273: 공지사항 리스트 UI 변경
  src/@types/announcement.ts
  src/components/Card/AnnounceCard/AnnounceList/index.tsx
  src/components/Card/AnnounceCard/index.test.tsx
  src/components/Card/AnnounceCard/index.tsx
  src/components/Card/InformCard/index.test.tsx
  src/components/Card/InformCard/index.tsx
  src/components/Carousel/index.tsx
  src/components/List/DepartmentList/index.test.tsx
  src/components/MajorProvider/index.tsx
  src/components/Modal/ConfirmModal/index.tsx
  src/constants/.gitkeep
  src/constants/announcement.ts
  src/constants/path.ts
  src/constants/placeholder-message.ts
  src/constants/toast-message.ts
  src/contexts/major.ts
  src/pages/Announcement/components/AnnounceContainer.tsx
  src/pages/Announcement/components/AnnounceNotFound.tsx
  src/pages/Announcement/components/AnnounceSearch.tsx
  src/pages/Announcement/components/AnnounceSearchList.tsx
  src/pages/Announcement/components/AnnounceTypeButtons.tsx
  src/pages/Announcement/components/index.ts
  src/pages/Announcement/index.tsx
  src/pages/Home/Home.test.tsx
  src/pages/Home/components/InformCardList.tsx
  src/pages/Home/index.tsx
  src/pages/MajorDecision/index.test.tsx
  src/utils/.gitkeep
  src/utils/router/openLink.ts
Labels: 💇‍♂️ style

#283 Refactor/#282: 프로젝트 폴더 구조 개펀
  src/App.tsx
  src/components/BodyLayout/index.tsx
  src/components/Card/AnnounceCard/index.test.tsx
  src/components/Card/InformCard/index.test.tsx
  src/components/Card/InformCard/index.tsx
  src/components/Common/Button/Toggle/index.tsx
  src/components/Common/Button/index.tsx
  src/components/Common/Icon/index.tsx
  src/components/Common/Image/index.tsx
  src/components/Common/Modal/AlertModal/index.tsx
  src/components/Common/Modal/ConfirmModal/index.tsx
  src/components/Common/Modal/Modals/index.tsx
  src/components/Common/Modal/SuggestionModal/index.tsx
  src/components/Common/Modal/index.tsx
  src/components/Common/Toast/Toasts/index.tsx
  src/components/Common/Toast/index.tsx
  src/components/FooterTab/index.tsx
  src/components/Header/index.tsx
  src/components/List/AnnounceList/Skeleton.tsx
  src/components/List/AnnounceList/index.tsx
  src/components/List/CollegeList/CollegeItem.tsx
  src/components/List/CollegeList/Skeleton.tsx
  src/components/List/CollegeList/index.tsx
  src/components/List/DepartmentList/DepartmentItem.tsx
  src/components/List/DepartmentList/Skeleton.tsx
  src/components/List/DepartmentList/index.test.tsx
  src/components/List/DepartmentList/index.tsx
  src/components/Providers/MajorProvider/index.tsx
  src/components/Providers/ModalsProvider/index.tsx
  src/components/Providers/OverlayProvider/index.tsx
  src/components/Providers/OverlayProvider/overlay.ts
  src/components/Providers/ToastsProvider/index.tsx
  src/components/Providers/index.ts
  src/components/SideBar/Content/index.tsx
  src/components/SideBar/index.tsx
  src/contexts/.gitkeep
  src/hooks/useModals.ts
  src/main.tsx
  src/pages/Announcement/components/AnnounceContainer.tsx
  src/pages/Announcement/components/AnnounceNotFound.tsx
  src/pages/Announcement/components/AnnounceSearch.tsx
  src/pages/Announcement/components/AnnounceTypeButtons.tsx
  src/pages/Home/Home.test.tsx
  src/pages/MajorDecision/index.test.tsx
  src/pages/Map/components/MapHeader.tsx
  src/pages/Map/components/RefreshButtons.tsx
  src/pages/Map/handlers/index.ts
  src/pages/My/index.test.tsx
  src/pages/My/index.tsx
  src/pages/Tip/index.tsx
  src/styles/.gitkeep
Labels: 🧑‍🔧 refactor, ⚒️ chore

#287 Style/#286: 꿀팁 페이지 디자인 수정
  public/assets/baekgyeong-speaker.png
  public/assets/baekgyeong-whalebe.png
  public/assets/pknu.png
  public/assets/tipImages/png/baekgyeong_camera.png
  public/assets/tipImages/png/baekgyeong_guide.png
  public/assets/tipImages/png/baekgyeong_hi.png
  public/assets/tipImages/png/baekgyeong_love.png
  public/assets/tipImages/png/baekgyeong_search.png
  public/assets/tipImages/png/baekgyeong_suprised.png
  public/assets/tipImages/png/baekgyeong_teach.png
  public/assets/tipImages/png/baekgyeong_underpin.png
  public/assets/tipImages/png/pknu.png
  public/assets/tipImages/webp/baekgyeong_camera.webp
  public/assets/tipImages/webp/baekgyeong_guide.webp
  public/assets/tipImages/webp/baekgyeong_hi.webp
  public/assets/tipImages/webp/baekgyeong_love.webp
  public/assets/tipImages/webp/baekgyeong_search.webp
  public/assets/tipImages/webp/baekgyeong_suprised.webp
  public/assets/tipImages/webp/baekgyeong_teach.webp
  public/assets/tipImages/webp/baekgyeong_underpin.webp
  public/assets/tipImages/webp/pknu.webp
  src/App.tsx
  src/components/Card/TipCard/TipImage.tsx
  src/components/Card/TipCard/TipSubTitle.tsx
  src/components/Card/TipCard/TipTitle.tsx
  src/components/Card/TipCard/domain/getTipCardSubElement.ts
  src/components/Card/TipCard/index.tsx
  src/components/Common/Image/index.tsx
  src/components/Header/index.tsx
  src/components/InformUpperLayout/InformSubTitle.tsx
  src/components/InformUpperLayout/InformTitle.tsx
  src/components/InformUpperLayout/InformTypeButton.tsx
  src/components/InformUpperLayout/domain/getInformUpperLayoutSubElement.ts
  src/components/InformUpperLayout/index.tsx
  src/components/List/TipCardList/index.tsx
  src/components/SideBar/Content/index.tsx
  src/components/SideBar/index.tsx
  src/constants/assets-path.ts
  src/constants/path.ts
  src/constants/tip.ts
  src/pages/Tip/index.tsx
Labels: ✨ feat, 🧑‍🔧 refactor, 💇‍♂️ style
