Repository GDSC-PKNU-Official/pknu-notice-front, pull requests merged in 2023-07, with the labels that each got.

#81 Feat/#80: PWA 적용
  index.html
  package.json
  public/icons/icon-128x128.png
  public/icons/icon-144x144.png
  public/icons/icon-152x152.png
  public/icons/icon-192x192.png
  public/icons/icon-384x384.png
  public/icons/icon-48x48.png
  public/icons/icon-512x512.png
  public/icons/icon-72x72.png
  public/icons/icon-96x96.png
  public/manifest.json
  public/mockServiceWorker.js
  src/@types/major.ts
  src/App.tsx
  src/components/Card/AnnounceCard/index.test.tsx
  src/components/Carousel/index.tsx
  src/components/FooterTab/index.tsx
  src/components/Header/index.tsx
  src/components/List/DepartmentList/index.tsx
  src/contexts/major.ts
  src/hooks/useRouter.ts
  src/mocks/handlers/announceHandlers.ts
  src/pages/Announcement/index.tsx
  src/pages/Home/Home.test.tsx
  src/pages/Home/index.tsx
  src/pages/My/index.tsx
  src/styles/Global/index.tsx
  sw.js
Labels: ⚙️ config, ✨ feat, 💇‍♂️ style

#83 Config/#82: nginx 구성
  docker-compose.prod.yml
  dockerfile.prod
  nginx/proxy/default.conf
  nginx/proxy/dockerfile
  nginx/static/default.conf
Labels: ⚙️ config, ✨ feat

#87 Refactor/#86: 배포된 백엔드와 통신되도록 엔드포인트 변경
  src/apis/Suspense/fetch-announce-list.ts
  src/components/Card/AnnounceCard/index.test.tsx
  src/components/List/CollegeList/index.tsx
  src/components/List/DepartmentList/index.tsx
  src/config/index.ts
  src/mocks/handlers/announceHandlers.ts
  src/mocks/handlers/majorHandlers.ts
Labels: 🧑‍🔧 refactor

#89 부리미 0.11v 배포
  docker-compose.prod.yml
  dockerfile.prod
  nginx/proxy/default.conf
  nginx/proxy/dockerfile
  nginx/static/default.conf
  src/apis/Suspense/fetch-announce-list.ts
  src/components/Card/AnnounceCard/index.test.tsx
  src/components/List/CollegeList/index.tsx
  src/components/List/DepartmentList/index.tsx
  src/config/index.ts
  src/mocks/handlers/announceHandlers.ts
  src/mocks/handlers/majorHandlers.ts
Labels: 🖥️ deploy

#91 부리미 0.11-2v 배포
  src/config/index.ts
Labels: 🖥️ deploy

#92 Feat/#88: 건의사항 작성시 감사 메세지 구현
  src/components/Button/index.tsx
  src/components/Modal/MajorModal/index.tsx
  src/components/Modal/SuggestionModal/SuggestionInput.tsx
  src/components/Modal/SuggestionModal/SuggestionThxMessage.tsx
  src/components/Modal/SuggestionModal/index.tsx
  src/components/Modal/index.tsx
  src/pages/My/index.tsx
Labels: ✨ feat, 🧑‍🔧 refactor, 💇‍♂️ style

#95 Fix: 서버 주소 변경
  src/config/index.ts
Labels: 🛠 fix

#100 Chore/#99: 백엔드 공지사항 데이터와 스키마 통일
  src/@types/announcement.ts
  src/components/Card/AnnounceCard/index.test.tsx
  src/components/Card/AnnounceCard/index.tsx
Labels: ⚒️ chore

#101 부리미 0.13v 배포
  src/@types/announcement.ts
  src/components/Card/AnnounceCard/index.test.tsx
  src/components/Card/AnnounceCard/index.tsx
Labels: 🖥️ deploy

#104 Feat/#93: 지도 페이지 구현
  .env.vault
  index.html
  src/App.tsx
  src/components/FooterTab/index.tsx
  src/components/Header/index.tsx
  src/components/Modal/MapBoundsLimitModal/index.tsx
  src/components/Modal/MapLevelLimitModal/index.tsx
  src/constants/pknu-map.ts
  src/pages/Map/MapLevelObserver.tsx
  src/pages/Map/MapboundaryObserver.tsx
  src/pages/Map/PknuBuildingNumbers.tsx
  src/pages/Map/index.tsx
Labels: ⚙️ config, ✨ feat, 💇‍♂️ style

#103 Fix/#102: 공지사항 선택 시 특정 학과는 공지 안보이는 에러 수정
  src/components/List/DepartmentList/index.test.tsx
  src/components/List/DepartmentList/index.tsx
  src/mocks/handlers/majorHandlers.ts
Labels: ✨ feat

#106 Feat/#105: 건의사항 작성 시 한번더 확인하기 구현 & 모달 전역상태로 변경
  src/@types/modals.ts
  src/@types/styles/icon.ts
  src/components/Card/InformCard/index.test.tsx
  src/components/Card/InformCard/index.tsx
  src/components/Icon/index.tsx
  src/components/List/DepartmentList/index.test.tsx
  src/components/List/DepartmentList/index.tsx
  src/components/Modal/AlertModal/index.tsx
  src/components/Modal/ConfirmModal/index.tsx
  src/components/Modal/Modals/index.tsx
  src/components/Modal/SuggestionModal/index.tsx
  src/components/Modal/index.tsx
  src/components/ModalsProvider/index.tsx
  src/constants/modal-messages.ts
  src/contexts/modals.ts
  src/hooks/useModals.ts
  src/main.tsx
  src/pages/Announcement/index.tsx
  src/pages/Home/Home.test.tsx
  src/pages/My/index.test.tsx
  src/pages/My/index.tsx
Labels: ✨ feat, 🧑‍🔧 refactor, 🔍 test, ⚒️ chore

#108 부리미 0.14v 배포
  .env.vault
  index.html
  src/@types/modals.ts
  src/@types/styles/icon.ts
  src/App.tsx
  src/components/Card/InformCard/index.test.tsx
  src/components/Card/InformCard/index.tsx
  src/components/FooterTab/index.tsx
  src/components/Header/index.tsx
  src/components/Icon/index.tsx
  src/components/List/DepartmentList/index.test.tsx
  src/components/List/DepartmentList/index.tsx
  src/components/Modal/AlertModal/index.tsx
  src/components/Modal/ConfirmModal/index.tsx
  src/components/Modal/MapBoundsLimitModal/index.tsx
  src/components/Modal/MapLevelLimitModal/index.tsx
  src/components/Modal/Modals/index.tsx
  src/components/Modal/SuggestionModal/index.tsx
  src/components/Modal/index.tsx
  src/components/ModalsProvider/index.tsx
  src/constants/modal-messages.ts
  src/constants/pknu-map.ts
  src/contexts/modals.ts
  src/hooks/useModals.ts
  src/main.tsx
  src/mocks/handlers/majorHandlers.ts
  src/pages/Announcement/index.tsx
  src/pages/Home/Home.test.tsx
  src/pages/Map/MapLevelObserver.tsx
  src/pages/Map/MapboundaryObserver.tsx
  src/pages/Map/PknuBuildingNumbers.tsx
  src/pages/Map/index.tsx
  src/pages/My/index.test.tsx
  src/pages/My/index.tsx
Labels: 🖥️ deploy

#111 Feat/#107: msw로 졸업요건링크 모킹 데이터 생성 & 졸업요건 카드 기능 구현
  src/components/Card/InformCard/index.test.tsx
  src/components/Card/InformCard/index.tsx
  src/components/Modal/MajorModal/index.test.tsx
  src/components/Modal/MajorModal/index.tsx
  src/components/Modal/MapBoundsLimitModal/index.tsx
  src/components/Modal/MapLevelLimitModal/index.tsx
  src/components/Modal/SuggestionModal/SuggestionInput.tsx
  src/components/Modal/SuggestionModal/SuggestionThxMessage.tsx
  src/mocks/browser.ts
  src/mocks/handlers/graudationHandler.ts
  src/pages/Home/index.tsx
  src/pages/Map/MapLevelObserver.tsx
  src/pages/Map/MapboundaryObserver.tsx
Labels: ⚙️ config, ✨ feat, 🔍 test

#110 Fix: 학부/학과와 전공 모두 있는경우 전공만 저장하도록 수정
  src/components/List/DepartmentList/index.test.tsx
  src/components/List/DepartmentList/index.tsx
Labels: 🛠 fix
