Repository GDSC-PKNU-Official/pknu-notice-front, pull requests merged in 2023-08, with the labels that each got.

#116 Feat/#112: 공지사항 페이지에서 학교, 학과 공지사항을 분리해서 보여줄 수 있는 UI 구현
  src/App.tsx
  src/components/Button/index.tsx
  src/components/Card/InformCard/index.test.tsx
  src/components/Card/InformCard/index.tsx
  src/mocks/handlers/announceHandlers.ts
  src/pages/Announcement/index.tsx
  src/pages/Home/index.tsx
Labels: ✨ feat, 🧑‍🔧 refactor, ⚒️ chore

#115 Style/#114: Header, Footer 크기 변경
  src/App.tsx
  src/components/FooterTab/index.tsx
  src/components/Header/index.tsx
Labels: 💇‍♂️ style

#118 Style/#113: 단과대/학과 선택 UI 개선
  src/components/Icon/index.tsx
  src/components/List/CollegeList/index.tsx
  src/components/List/DepartmentList/index.tsx
Labels: 🧑‍🔧 refactor, 💇‍♂️ style

#119 Feat/#117: 공지사항 고정, 일반 구분 UI 구현
  src/@types/announcement.ts
  src/@types/styles/icon.ts
  src/components/Card/AnnounceCard/AnnounceList/index.tsx
  src/components/Card/AnnounceCard/index.test.tsx
  src/components/Card/AnnounceCard/index.tsx
  src/components/Icon/index.tsx
  src/mocks/handlers/announceHandlers.ts
Labels: ✨ feat, 💇‍♂️ style

#121 부리미 0.14v 배포
  src/@types/announcement.ts
  src/@types/styles/icon.ts
  src/App.tsx
  src/components/Button/index.tsx
  src/components/Card/AnnounceCard/AnnounceList/index.tsx
  src/components/Card/AnnounceCard/index.test.tsx
  src/components/Card/AnnounceCard/index.tsx
  src/components/Card/InformCard/index.test.tsx
  src/components/Card/InformCard/index.tsx
  src/components/FooterTab/index.tsx
  src/components/Header/index.tsx
  src/components/Icon/index.tsx
  src/components/List/CollegeList/index.tsx
  src/components/List/DepartmentList/index.test.tsx
  src/components/List/DepartmentList/index.tsx
  src/components/Modal/MajorModal/index.test.tsx
  src/components/Modal/MajorModal/index.tsx
  src/components/Modal/MapBoundsLimitModal/index.tsx
  src/components/Modal/MapLevelLimitModal/index.tsx
  src/components/Modal/SuggestionModal/SuggestionInput.tsx
  src/components/Modal/SuggestionModal/SuggestionThxMessage.tsx
  src/mocks/browser.ts
  src/mocks/handlers/announceHandlers.ts
  src/mocks/handlers/graudationHandler.ts
  src/pages/Announcement/index.tsx
  src/pages/Home/index.tsx
  src/pages/Map/MapLevelObserver.tsx
  src/pages/Map/MapboundaryObserver.tsx
Labels: 🖥️ deploy

#123 Fix: 누락된 코드 추가
  src/App.tsx
Labels: 🛠 fix

#124 부리미 0.16v 배포
  src/App.tsx
Labels: 🖥️ deploy

#126 Fix: undefined 삭제
  src/mocks/handlers/announceHandlers.ts
  src/pages/Announcement/index.tsx
Labels: 🛠 fix

#127 부리미 0.17v 배포
  src/mocks/handlers/announceHandlers.ts
  src/pages/Announcement/index.tsx
Labels: 🖥️ deploy

#129 부리미 0.18v 배포
  src/apis/Suspense/fetch-announce-list.ts
  src/mocks/handlers/announceHandlers.ts
Labels: 🛠 fix

#131 Fix: 헤더 padding 크기 변경
  src/App.tsx
  src/components/Header/index.tsx
Labels: 🛠 fix

#133 Fix: 학과 선택하는 버튼 아래로 배치
  src/components/List/DepartmentList/index.tsx
Labels: 🛠 fix

#135 Fix: 모바일에서 확대 안되도록 수정
  index.html
Labels: 🛠 fix

#137 Feat/#136: 캐싱을 통해 오프라인에서도
  index.html
  package.json
  public/manifest.json
  vite.config.ts
  yarn.lock
Labels: ✨ feat

#139 Fix: 헤더, 푸터 높이 단위 vh 로 변경
  src/App.tsx
  src/components/FooterTab/index.tsx
  src/components/Header/index.tsx
Labels: 🛠 fix

#141 Fix: PWA 세로모드 고정, 디바이스의 풀 스크린으로 동작하도록 수정
  vite.config.ts
Labels: 🛠 fix

#147 Fix: viewport height 고정
  index.html
Labels: 🛠 fix

#148 부리미 v0.21 배포
  index.html
Labels: 🛠 fix, 🖥️ deploy

#150 Fix: 외부링크 이동 시 인앱 브라우저가 아닌 외부 브라우저로 열리도록 수정
  src/components/Card/AnnounceCard/index.tsx
Labels: 🛠 fix

#151 부리미 v0.22 배포
  src/components/Card/AnnounceCard/index.tsx
Labels: 🖥️ deploy

#153 Chore: 서버와 졸업요건 데이터 스키마 통일
  src/mocks/handlers/graudationHandler.ts
  src/pages/Home/index.tsx
Labels: ⚒️ chore

#157 Fix: Body의 높이 설정 안하는걸로 롤백
  src/App.tsx
Labels: 🛠 fix

#160 Style/#159: 헤더 푸터 그림자 추가
  src/components/Card/InformCard/index.tsx
  src/components/FooterTab/index.tsx
  src/components/Header/index.tsx
  src/pages/Home/index.tsx
  src/styles/Global/index.tsx
Labels: 💇‍♂️ style

#162 Fix: 잘못된 코드 수정
  src/pages/Home/index.tsx
Labels: 🛠 fix

#163 부리미 v0.23 배포
  src/App.tsx
  src/components/Card/InformCard/index.tsx
  src/components/FooterTab/index.tsx
  src/components/Header/index.tsx
  src/mocks/handlers/graudationHandler.ts
  src/pages/Home/index.tsx
  src/styles/Global/index.tsx
Labels: 🖥️ deploy

#164 Feat/#161: 알림 받을 수 있도록 기능 추가 & 마이페이지 디자인 개선
  public/manifest.json
  public/sw.js
  src/components/Button/Toggle/index.tsx
  src/components/List/DepartmentList/index.tsx
  src/hooks/urlBase64ToUint8Array.ts
  src/mocks/browser.ts
  src/mocks/handlers/subscribeHandler.ts
  src/mocks/server.ts
  src/pages/My/index.test.tsx
  src/pages/My/index.tsx
  src/styles/Global/index.tsx
  vite.config.ts
Labels: ✨ feat, 💇‍♂️ style

#165 Feat/#154: 지도 페이지 디자인 & 기능 개선
  public/assets/map1.png
  public/assets/map2.png
  src/@types/map.ts
  src/@types/styles/icon.ts
  src/App.tsx
  src/components/Icon/index.tsx
  src/constants/pknu-map.ts
  src/hooks/useUserLocation.ts
  src/pages/BodyLayout/index.tsx
  src/pages/Map/MapLevelObserver.tsx
  src/pages/Map/MapboundaryObserver.tsx
  src/pages/Map/PknuBuildingNumbers.tsx
  src/pages/Map/components/BuildingFilterButtons.tsx
  src/pages/Map/components/MapHeader.tsx
  src/pages/Map/components/PknuBuildingNumbers.tsx
  src/pages/Map/components/UserLocation.tsx
  src/pages/Map/handlers/distance-handler.ts
  src/pages/Map/handlers/limit-handler.ts
  src/pages/Map/handlers/overlay-handler.ts
  src/pages/Map/index.tsx
Labels: ⚙️ config, ✨ feat, 🧑‍🔧 refactor

#167 부리미 0.24v 배포
  public/assets/map1.png
  public/assets/map2.png
  public/manifest.json
  public/sw.js
  src/@types/map.ts
  src/@types/styles/icon.ts
  src/App.tsx
  src/components/Button/Toggle/index.tsx
  src/components/Icon/index.tsx
  src/components/List/DepartmentList/index.tsx
  src/constants/pknu-map.ts
  src/hooks/urlBase64ToUint8Array.ts
  src/hooks/useUserLocation.ts
  src/mocks/browser.ts
  src/mocks/handlers/subscribeHandler.ts
  src/mocks/server.ts
  src/pages/BodyLayout/index.tsx
  src/pages/Map/MapLevelObserver.tsx
  src/pages/Map/MapboundaryObserver.tsx
  src/pages/Map/PknuBuildingNumbers.tsx
  src/pages/Map/components/BuildingFilterButtons.tsx
  src/pages/Map/components/MapHeader.tsx
  src/pages/Map/components/PknuBuildingNumbers.tsx
  src/pages/Map/components/UserLocation.tsx
  src/pages/Map/handlers/distance-handler.ts
  src/pages/Map/handlers/limit-handler.ts
  src/pages/Map/handlers/overlay-handler.ts
  src/pages/Map/index.tsx
  src/pages/My/index.test.tsx
  src/pages/My/index.tsx
  src/styles/Global/index.tsx
  vite.config.ts
Labels: 🖥️ deploy

#170 Fix/#169: PWA 적용 안되는 문제 해결해보기
  public/manifest.json
  public/mockServiceWorker.js
  public/serviceWorker.js
  vite.config.ts
Labels: 🛠 fix

#175 Fix/#174: 개발환경에만 MSW가 서비스워커에 등록되도록 수정
  package.json
  public/mockServiceWorker.js
  public/serviceWorker.js
  src/main.tsx
Labels: 🛠 fix

#178 Feat/#177: PKNU Builder 에러 해결
  public/manifest.json
  public/screenshots/home-page.png
  public/screenshots/map-page.png
  public/screenshots/my-page.png
Labels: ✨ feat

#179 부리미 0.28 배포
  public/manifest.json
  public/screenshots/home-page.png
  public/screenshots/map-page.png
  public/screenshots/my-page.png
Labels: 🖥️ deploy

#180 Feat/#168: 구글 애널리틱스 붙이기
  src/App.tsx
  src/config/index.ts
  src/utils/routeChangeTracker.ts
Labels: ✨ feat

#182 Feat: 스토어 배포에 필요한 파일 추가
  public/.well-known/assetlinks.json
Labels: ✨ feat

#184 Feat: 개인정보처리방침 추가
  public/privacy.html
Labels: ✨ feat

#185 부리미 v0.29 배포
  public/.well-known/assetlinks.json
  public/privacy.html
  src/App.tsx
  src/config/index.ts
  src/utils/routeChangeTracker.ts
Labels: 🖥️ deploy

#187 Fix: 햄버거바 삭제
  src/components/Header/index.tsx
Labels: 🛠 fix

#190 Fix/#189: 모달창 크기 수정
  src/components/Modal/SuggestionModal/index.tsx
  src/components/Modal/index.tsx
Labels: 🛠 fix

#191 Style/#166: 공지사항 페이지 디자인 개선
  src/components/Card/AnnounceCard/Skeleton.tsx
  src/components/Card/AnnounceCard/index.tsx
  src/pages/Announcement/index.tsx
Labels: 💇‍♂️ style

#198 Style/#196: 부림이 앱 내부에서 사용할 폰트 설정
  index.html
  src/styles/Global/index.tsx
  src/styles/fonts/SpoqaHanSansNeo-Regular.eot
  src/styles/fonts/SpoqaHanSansNeo-Regular.ttf
  src/styles/fonts/SpoqaHanSansNeo-Regular.woff
  src/styles/fonts/SpoqaHanSansNeo-Regular.woff2
Labels: 💇‍♂️ style

#197 Feat/#84: 홈 화면에 캐러셀 추가
  jest.config.js
  package.json
  src/components/Card/InformCard/index.tsx
  src/components/Carousel/index.tsx
  src/constants/carouselInfo.ts
  src/jest.setup.ts
  src/pages/Home/index.tsx
  yarn.lock
Labels: ✨ feat

#200 부리미 0.30v 배포
  index.html
  jest.config.js
  package.json
  src/apis/Suspense/fetch-major-list.ts
  src/components/Card/AnnounceCard/Skeleton.tsx
  src/components/Card/AnnounceCard/index.tsx
  src/components/Card/InformCard/index.tsx
  src/components/Carousel/index.tsx
  src/components/Header/index.tsx
  src/components/List/CollegeList/CollegeItem.tsx
  src/components/List/CollegeList/index.tsx
  src/components/List/DepartmentList/DepartmentItem.tsx
  src/components/List/DepartmentList/index.test.tsx
  src/components/List/DepartmentList/index.tsx
  src/components/List/Skeleton/college.tsx
  src/components/List/Skeleton/department.tsx
  src/components/Modal/SuggestionModal/index.tsx
  src/components/Modal/index.tsx
  src/constants/carouselInfo.ts
  src/constants/department-length.ts
  src/jest.setup.ts
  src/pages/Announcement/index.tsx
  src/pages/Home/index.tsx
  src/styles/Global/index.tsx
  src/styles/ThemeProvider/theme.ts
  src/styles/emotion.d.ts
  src/styles/fonts/SpoqaHanSansNeo-Regular.eot
  src/styles/fonts/SpoqaHanSansNeo-Regular.ttf
  src/styles/fonts/SpoqaHanSansNeo-Regular.woff
  src/styles/fonts/SpoqaHanSansNeo-Regular.woff2
  yarn.lock
Labels: 🖥️ deploy

#202 Fix: 문자를 UTF-8 로 인코딩하도록 변경
  public/privacy.html
Labels: 🛠 fix

#204 부리미 0.31v 배포
  public/privacy.html
Labels: 🖥️ deploy

#205 Fix/#203: 공지사항, 학과선택 페이지 스타일 버그 수정
  src/components/List/CollegeList/CollegeItem.tsx
  src/components/List/CollegeList/index.tsx
  src/components/List/DepartmentList/DepartmentItem.tsx
  src/components/List/DepartmentList/index.tsx
  src/components/List/Skeleton/college.tsx
  src/components/List/Skeleton/department.tsx
  src/pages/Announcement/index.tsx
Labels: 💇‍♂️ style

#206 부리미 0.31v 배포
  src/components/List/CollegeList/CollegeItem.tsx
  src/components/List/CollegeList/index.tsx
  src/components/List/DepartmentList/DepartmentItem.tsx
  src/components/List/DepartmentList/index.tsx
  src/components/List/Skeleton/college.tsx
  src/components/List/Skeleton/department.tsx
  src/pages/Announcement/index.tsx
Labels: 🖥️ deploy

#208 Fix/#207: 부리미 -> 부림이로 롤백 및 헤더 수정
  public/manifest.json
  src/components/Header/index.tsx
Labels: ✨ feat

#212 Fix: 캐러셀 클릭 시 웨일비 홈으로 이동하도록 변경
  src/components/Carousel/index.tsx
Labels: 🛠 fix

#215 Docs: 부림이 프론트 리드미 작성
  README.md
Labels: 📖 docs

#216 Docs: 부림이 프론트 레파지토리 리드미 작성
  README.md
Labels: 📖 docs
