Repository GDSC-PKNU-Official/pknu-notice-front, pull requests merged in 2023-04, with the labels that each got.

#27 Chore: 라우팅 경로에 오타 수정
  src/App.tsx
Labels: ⚒️ chore

#25 Config/#24: @types 폴더 절대경로 설정
  src/components/Image/index.tsx
  src/utils/styles/size.ts
  tsconfig.path.json
  vite.config.ts
Labels: ⚙️ config

#29 Test: jest도 @상대경로 가능
  jest.config.js
Labels: 🔍 test

#36 Config/#32: theme 색깔 설정
  src/styles/ThemeProvider/theme.ts
  src/styles/emotion.d.ts
Labels: ⚙️ config

#42 Chore/#40: Issue 템플릿에 chore 추가
  .github/ISSUE_TEMPLATE/chore.md
Labels: ⚒️ chore

#46 Chore: theme 상수 컨벤션에 맞게 변경
  src/styles/ThemeProvider/index.tsx
  src/styles/ThemeProvider/theme.ts
  src/styles/emotion.d.ts
Labels: ⚒️ chore

#37 Feat/#23: Home 에서 사용할 Card 컴포넌트 구현
  src/@types/styles/icon.ts
  src/components/Card/InformCard/index.test.tsx
  src/components/Card/InformCard/index.tsx
  src/components/Icon/index.tsx
Labels: ✨ feat, 🔍 test

#39 Chore/#35: Jest 의 testEnvironment 변경
  jest.config.js
Labels: ⚒️ chore

#52 Feat: useRouter 커스텀 훅 생성
  src/hooks/useRouter.ts
Labels: ✨ feat

#51 Feat/#49: 전공상태 전역으로 관리하기 위한 Context 생성
  jest.config.js
  src/@types/major.ts
  src/components/MajorProvider/index.tsx
  src/contexts/major.ts
  src/hooks/useMajor.ts
  src/main.tsx
  src/pages/MajorDecision/index.test.tsx
  src/pages/MajorDecision/index.tsx
Labels: ⚙️ config, ✨ feat, 🔍 test

#58 Feat/#57: MSW 적용
  jest.config.js
  package.json
  src/jest.setup.ts
  src/mocks/handlers.ts
  src/mocks/server.ts
  yarn.lock
Labels: ⚙️ config, ✨ feat
