Repository GDSC-PKNU-Official/pknu-notice-front, pull requests merged in 2023-12, with the labels that each got.

#291 fix(Carousel): 웨일비 캐러셀에 모집기관과 운영기간을 나눠서 보여주도록 변경
  src/components/Carousel/index.tsx
Labels: 🛠 fix

#292 refactor/#289: 공지사항, FAQ 페이지에 UpperLayout 합성 컴포넌트 적용 & 팁 페이지 이미지 수정
  public/assets/tipImages/png/baekgyeong_camera.png
  public/assets/tipImages/png/baekgyeong_hand_love.png
  public/assets/tipImages/png/baekgyeong_hi.png
  public/assets/tipImages/png/baekgyeong_love.png
  public/assets/tipImages/png/baekgyeong_search.png
  public/assets/tipImages/png/baekgyeong_teach.png
  public/assets/tipImages/png/pknu.png
  public/assets/tipImages/webp/baekgyeong_camera.webp
  public/assets/tipImages/webp/baekgyeong_hand_love.webp
  public/assets/tipImages/webp/baekgyeong_hi.webp
  public/assets/tipImages/webp/baekgyeong_love.webp
  public/assets/tipImages/webp/baekgyeong_search.webp
  public/assets/tipImages/webp/baekgyeong_teach.webp
  public/assets/tipImages/webp/pknu.webp
  src/@types/styles/icon.ts
  src/components/Card/InformCard/index.test.tsx
  src/components/Card/InformCard/index.tsx
  src/components/Common/Icon/index.tsx
  src/components/FAQBox/index.tsx
  src/components/InformUpperLayout/InformSearchForm.tsx
  src/components/InformUpperLayout/domain/getInformUpperLayoutSubElement.ts
  src/components/InformUpperLayout/index.tsx
  src/components/List/AnnounceList/index.tsx
  src/constants/tip.ts
  src/pages/Announcement/components/AnnounceContainer.tsx
  src/pages/Announcement/components/AnnounceTypeButtons.tsx
  src/pages/Announcement/components/index.ts
  src/pages/FAQ/index.tsx
  src/pages/Home/components/InformCardList.tsx
Labels: 🧑‍🔧 refactor, 💇‍♂️ style

#296 Refactor/#293: 모달 합성 컴포넌트 적용 && 지도 페이지 의존성 주입 Context API 적용
  src/@types/modals.ts
  src/App.tsx
  src/components/Card/InformCard/index.test.tsx
  src/components/Card/InformCard/index.tsx
  src/components/Common/Button/Toggle/index.tsx
  src/components/Common/Modal/AlertModal/index.tsx
  src/components/Common/Modal/ConfirmModal/index.tsx
  src/components/Common/Modal/ModalButton.tsx
  src/components/Common/Modal/ModalTitle.tsx
  src/components/Common/Modal/Modals/index.tsx
  src/components/Common/Modal/SuggestionModal/index.tsx
  src/components/Common/Modal/domain/getModalSubElement.ts
  src/components/Common/Modal/index.tsx
  src/components/List/DepartmentList/DepartmentItem.tsx
  src/components/List/DepartmentList/index.test.tsx
  src/components/Providers/MapProvider/index.tsx
  src/components/Providers/OverlayProvider/index.tsx
  src/components/Providers/OverlayProvider/overlay.ts
  src/contexts/map.ts
  src/contexts/user-location.ts
  src/hooks/useBuildingTypes.ts
  src/hooks/useMap.ts
  src/hooks/useModals.ts
  src/hooks/useOverlays.ts
  src/hooks/useUserLocation.ts
  src/pages/Map/components/FilterButtons.tsx
  src/pages/Map/components/MapHeader.tsx
  src/pages/Map/components/PknuMap.tsx
  src/pages/Map/components/RefreshButtons.tsx
  src/pages/Map/components/index.ts
  src/pages/Map/index.tsx
  src/pages/My/index.test.tsx
  src/pages/My/index.tsx
  src/utils/map/get-building-info.ts
  src/utils/map/location-permission.ts
Labels: ✨ feat, 🧑‍🔧 refactor

#299 feat/#294 : 건의사항 페이지 구현
  src/App.tsx
  src/apis/suggestion/post-suggestion.ts
  src/pages/Suggestion/index.tsx
Labels: ✨ feat

#297 Feat/#264: 어학 공지사항 기능 추가
  src/@types/styles/icon.ts
  src/apis/Suspense/fetch-announce-list.ts
  src/components/Common/Icon/index.tsx
  src/components/InformUpperLayout/InformSearchForm.tsx
  src/constants/announcement.ts
  src/constants/path.ts
  src/constants/tip.ts
  src/pages/Announcement/components/AnnounceContainer.tsx
  src/pages/Announcement/index.tsx
  src/pages/Home/components/InformHalfCard.tsx
  src/pages/Home/index.tsx
  src/styles/ThemeProvider/theme.ts
  src/styles/emotion.d.ts
Labels: ✨ feat

#301 chore/#300 : 건의사항 페이지에서 사용하는 모달을 합성 컴포넌트로 변경
  src/pages/Suggestion/index.tsx
Labels: ⚒️ chore

#304 Fix/#303: 사용하지 않는 파일 삭제 & TipData 타입 변경
  src/components/List/TipCardList/index.tsx
  src/constants/tip.ts
  src/hooks/useLocationHandler.ts
Labels: 🛠 fix
