Repository GDSC-PKNU-Official/pknu-notice-front, pull requests merged in 2023-09, with the labels that each got.

#220 Refactor/#217: 지도 페이지의 하단 텍스트를 모달로 변경 & 사용자 위치 처리 로직 커스텀 훅 구현
  src/components/Modal/AlertModal/index.tsx
  src/constants/pknu-map.ts
  src/hooks/useLocationHandler.ts
  src/hooks/useUserLocation.ts
  src/pages/Map/components/BuildingFilterButtons.tsx
  src/pages/Map/components/MapHeader.tsx
  src/pages/Map/components/PknuBuildingNumbers.tsx
  src/pages/Map/components/UserLocation.tsx
  src/pages/Map/handlers/distance-handler.ts
  src/pages/Map/handlers/limit-handler.ts
  src/pages/Map/handlers/overlay-handler.ts
  src/pages/Map/index.tsx
Labels: ✨ feat, 🧑‍🔧 refactor, ⚒️ chore

#219 Feat: push 알림 클릭 시 본인 학과 공지사항 페이지로 이동하도록 추가
  public/sw.js
Labels: ✨ feat

#221 부리미 0.32v 배포
  README.md
  public/manifest.json
  public/sw.js
  src/components/Carousel/index.tsx
  src/components/Header/index.tsx
  src/components/Modal/AlertModal/index.tsx
  src/constants/pknu-map.ts
  src/hooks/useLocationHandler.ts
  src/hooks/useUserLocation.ts
  src/pages/Map/components/BuildingFilterButtons.tsx
  src/pages/Map/components/MapHeader.tsx
  src/pages/Map/components/PknuBuildingNumbers.tsx
  src/pages/Map/components/UserLocation.tsx
  src/pages/Map/handlers/distance-handler.ts
  src/pages/Map/handlers/limit-handler.ts
  src/pages/Map/handlers/overlay-handler.ts
  src/pages/Map/index.tsx
Labels: 🖥️ deploy

#223 Refactor/#210: 모달 state, dispatch 컨텍스트 분리
  src/@types/modals.ts
  src/components/Card/InformCard/index.test.tsx
  src/components/Card/InformCard/index.tsx
  src/components/List/DepartmentList/DepartmentItem.tsx
  src/components/Modal/Modals/index.tsx
  src/components/Modal/SuggestionModal/index.tsx
  src/components/ModalsProvider/index.tsx
  src/constants/modal-messages.ts
  src/contexts/modals.ts
  src/hooks/useLocationHandler.ts
  src/hooks/useModals.ts
  src/pages/Announcement/index.tsx
  src/pages/Map/components/MapHeader.tsx
  src/pages/Map/handlers/limit-handler.ts
  src/pages/Map/handlers/overlay-handler.ts
  src/pages/My/index.test.tsx
  src/pages/My/index.tsx
Labels: 🧑‍🔧 refactor

#225 Style/#224: FooterTab 높이 증가
  src/components/FooterTab/index.tsx
  src/components/List/DepartmentList/DepartmentItem.tsx
  src/pages/Announcement/index.tsx
  src/pages/BodyLayout/index.tsx
  src/pages/Map/index.tsx
Labels: 💇‍♂️ style

#230 Refactor/#226: 캐러셀 리팩토링
  src/components/Carousel/index.tsx
  src/mocks/handlers/announceHandlers.ts
  src/pages/Home/index.tsx
Labels: 🧑‍🔧 refactor

#233 fix/#229 : 학과 공지사항 페이지로 바로 이동했을 경우, bottom-bar 위치 에러 해결
  src/pages/Announcement/index.tsx
Labels: 🛠 fix

#232 Feat/#231: 공지사항 리스트, 단과대/학과 선택 리스트 클릭 애니메이션 추가
  src/components/Card/AnnounceCard/index.tsx
  src/components/List/CollegeList/CollegeItem.tsx
  src/components/List/DepartmentList/DepartmentItem.tsx
  src/pages/Home/index.tsx
Labels: ✨ feat

#210 fix: 배경색 기본색으로 롤백
  src/styles/Global/index.tsx
  src/styles/ThemeProvider/theme.ts
Labels: 🧑‍🔧 refactor

#234 부림이 0.33v 배포
  src/@types/modals.ts
  src/components/Card/AnnounceCard/index.tsx
  src/components/Card/InformCard/index.test.tsx
  src/components/Card/InformCard/index.tsx
  src/components/Carousel/index.tsx
  src/components/FooterTab/index.tsx
  src/components/List/CollegeList/CollegeItem.tsx
  src/components/List/DepartmentList/DepartmentItem.tsx
  src/components/Modal/Modals/index.tsx
  src/components/Modal/SuggestionModal/index.tsx
  src/components/ModalsProvider/index.tsx
  src/constants/modal-messages.ts
  src/contexts/modals.ts
  src/hooks/useLocationHandler.ts
  src/hooks/useModals.ts
  src/mocks/handlers/announceHandlers.ts
  src/pages/Announcement/index.tsx
  src/pages/BodyLayout/index.tsx
  src/pages/Home/index.tsx
  src/pages/Map/components/MapHeader.tsx
  src/pages/Map/handlers/limit-handler.ts
  src/pages/Map/handlers/overlay-handler.ts
  src/pages/Map/index.tsx
  src/pages/My/index.test.tsx
  src/pages/My/index.tsx
  src/styles/Global/index.tsx
  src/styles/ThemeProvider/theme.ts
Labels: 🖥️ deploy

#236 Fix: whalebe 엔드포인트 오타 수정
  src/components/Carousel/index.tsx
  src/mocks/handlers/announceHandlers.ts
Labels: 🛠 fix

#237 부림이 0.34v 배포
  src/components/Carousel/index.tsx
  src/mocks/handlers/announceHandlers.ts
Labels: 🖥️ deploy

#239 Fix/#238: 캐러셀 일부 수정
  src/components/Carousel/index.tsx
  src/pages/Home/index.tsx
Labels: 🛠 fix

#241 Fix: 공지사항 카드 글자색 검은색으로 롤백
  src/components/Card/InformCard/index.tsx
Labels: 🛠 fix

#243 Feat: aasa 파일 추가
  public/.well-known/apple-app-site-association
Labels: ✨ feat, 🛠 fix

#244 부림이 v0.34 배포
  public/.well-known/apple-app-site-association
  src/components/Card/InformCard/index.tsx
  src/components/Carousel/index.tsx
  src/pages/Home/index.tsx
Labels: 🖥️ deploy

#247 Feat/#245: 알림 설정에 모달창으로 정보 추가
  src/components/Modal/ConfirmModal/index.tsx
  src/constants/modal-messages.ts
  src/pages/My/index.tsx
Labels: ✨ feat

#248 부림이 v0.35 배포
  src/components/Modal/ConfirmModal/index.tsx
  src/constants/modal-messages.ts
  src/pages/My/index.tsx
Labels: 🖥️ deploy

#250 Fix/#249: 알림 구독 실패 시 에러 핸들링 추가
  src/constants/modal-messages.ts
  src/pages/My/index.tsx
Labels: 🛠 fix

#252 Fix: google play console 의 fingerprints 값 추가
  public/.well-known/assetlinks.json
Labels: 🛠 fix

#253 부림이 v0.36 배포
  public/.well-known/assetlinks.json
  src/constants/modal-messages.ts
  src/pages/My/index.tsx
Labels: 🖥️ deploy

#255 Fix: 'PushManager' in window 코드 제거
  src/pages/My/index.tsx
Labels: 🛠 fix

#256 부림이 v0.37 배포
  src/pages/My/index.tsx
Labels: 🖥️ deploy
