Repository GDSC-PKNU-Official/pknu-notice-front, pull requests merged in 2024-01, with the labels that each got.

#307 Feat/#306: 채용공지사항 기능 추가
  src/components/Card/AnnounceCard/index.tsx
  src/pages/Announcement/index.tsx
Labels: ✨ feat

#309 Refactor/#308: 사용자의 전공 상태 정보(useState) 삭제
  src/components/Card/InformCard/index.test.tsx
  src/components/Providers/MajorProvider/index.tsx
  src/components/Providers/MajorProvider/major-storage.ts
  src/components/Providers/OverlayProvider/index.tsx
  src/contexts/major.ts
  src/hooks/useMajor.ts
  src/pages/MajorDecision/index.test.tsx
Labels: ✨ feat, 🧑‍🔧 refactor

#310 부림이 0.4.5v 배포
  src/components/Card/AnnounceCard/index.tsx
  src/components/Card/InformCard/index.test.tsx
  src/components/Providers/MajorProvider/index.tsx
  src/components/Providers/MajorProvider/major-storage.ts
  src/components/Providers/OverlayProvider/index.tsx
  src/contexts/major.ts
  src/hooks/useMajor.ts
  src/pages/Announcement/index.tsx
  src/pages/MajorDecision/index.test.tsx
Labels: 🖥️ deploy

#312 Fix/#311: 공지사항 페이지에서 히스토리 관리 추가
  src/hooks/useRouter.ts
  src/pages/Announcement/components/AnnounceContainer.tsx
Labels: ✨ feat, 🛠 fix
